### ISSUE TITLE
About the data number of sepsis_cohort.py's result 

### ISSUE THREAD

**Issue by QZJ-2003** [aleksa-sukovic/iclr2024-reward-design-for-justifiable-rl#1]
The 2024 ICLR paper mentions that 'We focus our analysis on patients that fulfill Sepsi-3 criteria (Singer et al., 2016), 18,585 in total'. However, I use MIMIC-III v1.4 to reproduce the data process of this code, and then the result number of `.csv` file is 18,918. Why do I have more data? How can I check the reason? And How can I verify the correctness of my result?

**Comment by aleksa-sukovic** [comment]
Have you used the [train/val/test generator script](https://github.com/aleksa-sukovic/iclr2024-reward-design-for-justifiable-rl/blob/master/argo/scripts/data.py) from this repo? The only post-processing (that can exclude patients) done to the *.csv files generated by the [MIMIC-sepsis extraction script](https://github.com/microsoft/mimic_sepsis) is skipping of trajectories with length=1 (see [here](https://github.com/aleksa-sukovic/iclr2024-reward-design-for-justifiable-rl/blob/master/argo/scripts/data.py#L40-L41)). The number reported in the paper is `len(train_dict) + len(val_dict) + len(test_dict) = 18,585`.
